// AUTOGENERATED FILE - DO NOT EDIT

var pt = window.PropTypes;
var pk = window['dash_week_range_picker'];

pk.WeekRangePickerInput.propTypes = {value:pt.arrayOf(pt.string),
 minDate:pt.string,
 maxDate:pt.string,
 presets:pt.arrayOf(pt.shape({label:pt.string,value:pt.arrayOf(pt.string)})),
 placeholder:pt.string,
 clearable:pt.bool,
 closeOnChange:pt.bool,
 withWeekNumbers:pt.bool,
 highlightToday:pt.bool,
 firstDayOfWeek:pt.number,
 theme:pt.object,
 forceColorScheme:pt.oneOf(['light','dark']),
 className:pt.string,
 style:pt.any,
 persistence:pt.oneOfType([pt.string,pt.number,pt.bool]),
 persisted_props:pt.arrayOf(pt.string),
 persistence_type:pt.oneOf(['local','session','memory']),
 id:pt.oneOfType([pt.string,pt.object]),
 setProps:pt.any,
 loading_state:pt.shape({is_loading:pt.bool,prop_name:pt.string,component_name:pt.string})};
